spring:
  application:
    name: muse
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/muse
    username: postgres
    password: 1533

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:

      hibernate:
        format_sql: true


recommender:
  base-url: http://localhost:8000/api/v1
